admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Default:index }

createAteliers:
    path:     /createAteliers
    defaults: { _controller: AdminBundle:Default:createAteliers }

