<?php

namespace AdminBundle\Repository;

/**
 * videosThemesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class videosThemesRepository extends \Doctrine\ORM\EntityRepository
{
}
