<?php

namespace PlanningBundle\Repository;

/**
 * ConferencesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConferencesRepository extends \Doctrine\ORM\EntityRepository
{
    public function remove($id){
        return $this->createQueryBuilder('a')
            ->delete()
            ->where("a.id = :id")
            ->setParameter('id', $id)
            ->getQuery()
            ->getResult();

    }
}
